/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pemilihan_Dokter;

/**
 *
 * @author elvina
 */
public class Pemilihan_Dokter extends javax.swing.JFrame {

    /**
     * Creates new form Pemilihan_Dokter
     */
    public Pemilihan_Dokter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtxtfakul = new javax.swing.JTextField();
        jtxthari = new javax.swing.JTextField();
        jtxtkewar = new javax.swing.JTextField();
        jtxtstatus = new javax.swing.JTextField();
        jtxtstudi = new javax.swing.JTextField();
        jtxtjenis = new javax.swing.JTextField();
        jtxtusia = new javax.swing.JTextField();
        jtxtalamat = new javax.swing.JTextField();
        jtxtnama = new javax.swing.JTextField();
        jconadokt = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "IDENTITAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel1.setAlignmentX(15.0F);
        jPanel1.setAlignmentY(15.0F);
        jPanel1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Nama");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 50, 60, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Alamat");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 90, 70, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Usia");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 130, 60, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Jenis Kelamin");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(70, 170, 100, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Bidang Studi");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(70, 210, 110, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Status");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(70, 250, 70, 17);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Kewarganegaraan");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(70, 290, 120, 17);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Hari");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(70, 330, 110, 17);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Fakultas");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(70, 370, 110, 17);

        jtxtfakul.setEditable(false);
        jPanel1.add(jtxtfakul);
        jtxtfakul.setBounds(210, 360, 320, 30);

        jtxthari.setEditable(false);
        jPanel1.add(jtxthari);
        jtxthari.setBounds(210, 320, 320, 30);

        jtxtkewar.setEditable(false);
        jPanel1.add(jtxtkewar);
        jtxtkewar.setBounds(210, 280, 320, 30);

        jtxtstatus.setEditable(false);
        jPanel1.add(jtxtstatus);
        jtxtstatus.setBounds(210, 240, 320, 30);

        jtxtstudi.setEditable(false);
        jPanel1.add(jtxtstudi);
        jtxtstudi.setBounds(210, 200, 320, 30);

        jtxtjenis.setEditable(false);
        jPanel1.add(jtxtjenis);
        jtxtjenis.setBounds(210, 160, 320, 30);

        jtxtusia.setEditable(false);
        jPanel1.add(jtxtusia);
        jtxtusia.setBounds(210, 120, 320, 30);

        jtxtalamat.setEditable(false);
        jPanel1.add(jtxtalamat);
        jtxtalamat.setBounds(210, 80, 320, 30);

        jtxtnama.setEditable(false);
        jPanel1.add(jtxtnama);
        jtxtnama.setBounds(210, 40, 320, 30);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(30, 140, 600, 410);

        jconadokt.setBackground(new java.awt.Color(255, 204, 204));
        jconadokt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jconadokt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Salah Satu", "I GB Surya Ari K", "I PT Putra Dharmawan", "I GB Surya Negara" }));
        jconadokt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jconadoktActionPerformed(evt);
            }
        });
        jPanel2.add(jconadokt);
        jconadokt.setBounds(250, 100, 310, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Pilih Dokter");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(100, 110, 120, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Pemilihan Dokter");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(250, 30, 230, 29);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 580));

        setBounds(0, 0, 678, 621);
    }// </editor-fold>//GEN-END:initComponents

    private void jconadoktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jconadoktActionPerformed

        if(jconadokt.getSelectedItem().equals("I GB Surya Ari K")){
            jtxtnama.setText("I GB Surya Ari K");
            jtxtalamat.setText("Jl. Kaba-kaba, Tabanan");
            jtxtusia.setText("25 Tahun");
            jtxtjenis.setText("Laki-Laki"); 
            jtxtstudi.setText("Pendidikan Kedokteran");
            jtxtstatus.setText("Menikah");
            jtxtkewar.setText("Indonesia");
            jtxthari.setText("Senin & Kamis");
            jtxtfakul.setText("Kedokteran");
        }
       
        else if(jconadokt.getSelectedItem().equals("I PT Putra Dharmawan")){
            jtxtnama.setText("I PT Putra Dharmawan");
            jtxtalamat.setText("Jl. Bongan, Tabanan");
            jtxtusia.setText("25 Tahun");
            jtxtjenis.setText("Laki-Laki"); 
            jtxtstudi.setText("Pendidikan Keperawatan");
            jtxtstatus.setText("Belum Menikah");
            jtxtkewar.setText("Indonesia");
            jtxthari.setText("Selasa & Jumat");
            jtxtfakul.setText("Kedokteran");
        }
        
        else if(jconadokt.getSelectedItem().equals("I GB Surya Negara")){
            jtxtnama.setText("I GB Surya Negara");
            jtxtalamat.setText("Jl. Kaba-kaba, Tabanan");
            jtxtusia.setText("29 Tahun");
            jtxtjenis.setText("Laki-Laki"); 
            jtxtstudi.setText("Pendidikan Kebidanan");
            jtxtstatus.setText("Menikah");
            jtxtkewar.setText("Indonesia");
            jtxthari.setText("Rabu-Jumat");
            jtxtfakul.setText("Kedokteran");
        }
    }//GEN-LAST:event_jconadoktActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pemilihan_Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pemilihan_Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pemilihan_Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pemilihan_Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pemilihan_Dokter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jconadokt;
    private javax.swing.JTextField jtxtalamat;
    private javax.swing.JTextField jtxtfakul;
    private javax.swing.JTextField jtxthari;
    private javax.swing.JTextField jtxtjenis;
    private javax.swing.JTextField jtxtkewar;
    private javax.swing.JTextField jtxtnama;
    private javax.swing.JTextField jtxtstatus;
    private javax.swing.JTextField jtxtstudi;
    private javax.swing.JTextField jtxtusia;
    // End of variables declaration//GEN-END:variables
}
