/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tugas_Pratikum2;

/**
 *
 * @author elvina
 */
public class Tugas_Pratikum2 extends javax.swing.JFrame {

    /**
     * Creates new form Tugas_Pratikum2
     */
    public Tugas_Pratikum2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtxtwaktu = new javax.swing.JTextField();
        jtxtspesial = new javax.swing.JTextField();
        jtxtkewar = new javax.swing.JTextField();
        jtxtstatus = new javax.swing.JTextField();
        jtxtgol = new javax.swing.JTextField();
        jtxtjenis = new javax.swing.JTextField();
        jtxtusia = new javax.swing.JTextField();
        jtxtalamat = new javax.swing.JTextField();
        jtxtnama = new javax.swing.JTextField();
        jconadokt = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "IDENTITAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel1.setAlignmentX(15.0F);
        jPanel1.setAlignmentY(15.0F);
        jPanel1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Nama");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 50, 60, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Alamat");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 90, 70, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Usia");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 130, 60, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Jenis Kelamin");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(70, 170, 100, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Golongan Darah");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(70, 210, 110, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Status");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(70, 250, 70, 17);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Kewarganegaraan");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(70, 290, 120, 17);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Waktu Praktek");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(70, 330, 110, 17);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Dokter Spesialis");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(70, 370, 110, 17);

        jtxtwaktu.setEditable(false);
        jPanel1.add(jtxtwaktu);
        jtxtwaktu.setBounds(210, 360, 320, 30);

        jtxtspesial.setEditable(false);
        jPanel1.add(jtxtspesial);
        jtxtspesial.setBounds(210, 320, 320, 30);

        jtxtkewar.setEditable(false);
        jPanel1.add(jtxtkewar);
        jtxtkewar.setBounds(210, 280, 320, 30);

        jtxtstatus.setEditable(false);
        jPanel1.add(jtxtstatus);
        jtxtstatus.setBounds(210, 240, 320, 30);

        jtxtgol.setEditable(false);
        jPanel1.add(jtxtgol);
        jtxtgol.setBounds(210, 200, 320, 30);

        jtxtjenis.setEditable(false);
        jPanel1.add(jtxtjenis);
        jtxtjenis.setBounds(210, 160, 320, 30);

        jtxtusia.setEditable(false);
        jPanel1.add(jtxtusia);
        jtxtusia.setBounds(210, 120, 320, 30);

        jtxtalamat.setEditable(false);
        jPanel1.add(jtxtalamat);
        jtxtalamat.setBounds(210, 80, 320, 30);

        jtxtnama.setEditable(false);
        jPanel1.add(jtxtnama);
        jtxtnama.setBounds(210, 40, 320, 30);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(30, 140, 600, 410);

        jconadokt.setBackground(new java.awt.Color(255, 204, 204));
        jconadokt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jconadokt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Salah Satu", "DR. Farras Yassar", "DR. Anisa Putri", "DR. I GB Surya Ari K" }));
        jconadokt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jconadoktActionPerformed(evt);
            }
        });
        jPanel2.add(jconadokt);
        jconadokt.setBounds(250, 100, 310, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Pilih Dokter");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(100, 110, 120, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Pemilihan Dokter");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(250, 30, 230, 29);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 580));

        setBounds(0, 0, 672, 590);
    }// </editor-fold>//GEN-END:initComponents

    private void jconadoktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jconadoktActionPerformed

        if(jconadokt.getSelectedItem().equals("DR. Farras Yassar")){
            jtxtnama.setText("DR. Farras Yassar ");
            jtxtalamat.setText("Jl. Surabaya 16, Malang");
            jtxtusia.setText("20 Tahun");
            jtxtjenis.setText("Laki-Laki");
            jtxtgol.setText("A");
            jtxtstatus.setText("Belum Menikah ");
            jtxtkewar.setText("Indonesia");
            jtxtspesial.setText("Dokter Umum");
            jtxtwaktu.setText(" Pagi (07.00-15.00)");
        }

        else if(jconadokt.getSelectedItem().equals("DR. Anisa Putri")){
            jtxtnama.setText("DR. Anisa Putri");
            jtxtalamat.setText("Jl. Veteran 3, Malang");
            jtxtusia.setText("20 Tahun");
            jtxtjenis.setText("Perempuan");
            jtxtgol.setText("O");
            jtxtstatus.setText("Belum Menikah ");
            jtxtkewar.setText("Indonesia");
            jtxtspesial.setText("Dokter Gigi");
            jtxtwaktu.setText("Sore (16.00-22.00)");
        }

        else if(jconadokt.getSelectedItem().equals("DR. I GB Surya Ari K")){
            jtxtnama.setText("DR.I GB Surya Ari K");
            jtxtalamat.setText("Jl. Kaba-kaba 9, Tabanan");
            jtxtusia.setText("20 Tahun");
            jtxtjenis.setText("Laki-Laki");
            jtxtgol.setText("O");
            jtxtstatus.setText("Belum Menikah ");
            jtxtkewar.setText("Indonesia");
            jtxtspesial.setText("Dokter Bedah");
            jtxtwaktu.setText("Malam (22.00-06.00)");
        }
    }//GEN-LAST:event_jconadoktActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tugas_Pratikum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tugas_Pratikum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tugas_Pratikum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tugas_Pratikum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tugas_Pratikum2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jconadokt;
    private javax.swing.JTextField jtxtalamat;
    private javax.swing.JTextField jtxtgol;
    private javax.swing.JTextField jtxtjenis;
    private javax.swing.JTextField jtxtkewar;
    private javax.swing.JTextField jtxtnama;
    private javax.swing.JTextField jtxtspesial;
    private javax.swing.JTextField jtxtstatus;
    private javax.swing.JTextField jtxtusia;
    private javax.swing.JTextField jtxtwaktu;
    // End of variables declaration//GEN-END:variables
}
